name: Deploy to AWS

on:
  push:
    branches: [master]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_BACKEND: my-fashion-trunk-backend
  ECR_REPOSITORY_FRONTEND: my-fashion-trunk-frontend
  ECS_CLUSTER: my-fashion-trunk-cluster
  ECS_SERVICE_BACKEND: backend-service
  ECS_SERVICE_FRONTEND: frontend-service
  ECS_TASK_DEFINITION_BACKEND: backend-task-definition
  ECS_TASK_DEFINITION_FRONTEND: frontend-task-definition

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Backend Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$GITHUB_SHA ./backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$GITHUB_SHA

      - name: Build and push Frontend Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$GITHUB_SHA ./frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$GITHUB_SHA

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION_BACKEND --query taskDefinition > backend-task-def.json
          aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION_FRONTEND --query taskDefinition > frontend-task-def.json

      - name: Fill in the new image ID in the Amazon ECS task definitions
        id: task-def
        run: |
          # Update backend task definition
          sed -i "s|$ECR_REPOSITORY_BACKEND:.*|$ECR_REPOSITORY_BACKEND:$GITHUB_SHA|g" backend-task-def.json
          # Update frontend task definition
          sed -i "s|$ECR_REPOSITORY_FRONTEND:.*|$ECR_REPOSITORY_FRONTEND:$GITHUB_SHA|g" frontend-task-def.json

      - name: Deploy Amazon ECS task definitions
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE_BACKEND --task-definition $ECS_TASK_DEFINITION_BACKEND --force-new-deployment
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE_FRONTEND --task-definition $ECS_TASK_DEFINITION_FRONTEND --force-new-deployment
